version: '3'
services:
    vsftpd:
      image: panubo/vsftpd:latest
      environment:
        - FTP_USER=ftp
        - FTP_PASSWORD=ftp
      volumes:
        - /root/practicas:/srv
      expose:
        - 21
      network_mode: host