version: "3"

services:
  api-gateway:
    image: spinzon12/bbs71-api-gateway:2.0
    ports:
      - "3000:3000"
    links:
      - microuser
      - microairlines
      - microairports
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu

  microuser:
    image: spinzon12/bbs71-microuser:1.0

  microairlines:
    image: spinzon12/bbs71-microairlines:1.0

  microairports:
    image: spinzon12/bbs71-microairports:1.0

  app-1:
    image: spinzon12/bbs71-app:1.0
    depends_on:
      - api-gateway
    deploy:
      placement:
        constraints:
          - node.hostname == clienteUbuntu

  app-2:
    image: spinzon12/bbs71-app:1.0
    depends_on:
      - api-gateway
    deploy:
      placement:
        constraints:
          - node.hostname == clienteUbuntu

  haproxy:
    image: spinzon12/bbs71-haproxy:2.0
    ports:
      - "1080:80"
    links:
      - app-1
      - app-2
    deploy:
      placement:
        constraints:
          - node.hostname == servidorUbuntu
